apiVersion: v1
kind: ServiceAccount
metadata:
  name: aura
  namespace: aura
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aura
  namespace: aura
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aura
  namespace: aura
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aura
subjects:
- kind: ServiceAccount
  name: aura
  namespace: aura
