apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aura.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "aura.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
