apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aura.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "aura.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
