apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aura.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "aura.labels" . | nindent 4 }}
